![*INTERTECHNICA - SOLON EDUCATIONAL PROGRAMS - TECHNOLOGY LINE*](https://solon.intertechnica.com/assets/IntertechnicaSolonEducationalPrograms-TechnologyLine.png)

# Python for Data Processing - Creating Arrays

*Numpy allows various methods for creating arrays starting from creation using basic types to loading data from external sources*.

Initializing environment for machine learning use:

In [1]:
!python -m pip install numpy

## 1. Creating from arrays and lists

An array can be created from simple Python arrays:

In [2]:
import numpy as np

In [3]:
x_1d = np.array([ 1,   2,   3,   4,   5,   6,   7,   8,   9,  10])
print(x_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
x_2d = np.array(
      [[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

print(x_2d)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


Numpy also allows creation of arrays from lists:

In [5]:
x_1d_list = np.array(( 1,   2,   3,   4,   5,   6,   7,   8,   9,  10))

By using lists it is possible to create **arrays of complex types** as well:

In [6]:
x_1d_complex = np.array(
    [("One", 1), ("Two", 2), ("Three", 3)],
    dtype=[("Literal Form", "U10"), ("Numeric Value", "i1")])

print(x_1d_complex)

[('One', 1) ('Two', 2) ('Three', 3)]


In [7]:
print(x_1d_complex["Literal Form"])

['One' 'Two' 'Three']


In [8]:
print(x_1d_complex["Numeric Value"])

[1 2 3]


## 2. Creating via dedicated functions

Numpy allows creation of arrays using dedicated numpy functions.

One of these functions is **arange** which creates a uni-dimensional array with each element having its ordinal value starting from 0.

In [9]:
x_1d_arange = np.arange(10)
print(x_1d_arange)

[0 1 2 3 4 5 6 7 8 9]


Another useful function is **empty** which creates arrays with non-initialized content and various dimensions. 

In [10]:
x_1d_empty = np.empty(10)
print(x_1d_empty)

[3.69929606e-033 1.10553748e-046 1.73681700e-047 9.14033447e-043
 5.01163104e+217 5.49419094e-143 9.80058441e+252 1.30304358e-142
 2.14027814e+161 9.29590747e+242]


In [11]:
x_2d_empty = np.empty((10,10))
print(x_2d_empty)

[[6.91537208e-310 9.88131292e-324 4.94065646e-324 1.38338381e-322
  6.91538752e-310 6.91537208e-310 4.94065646e-324 2.75859453e-313
  2.75859453e-313 4.64333467e-310]
 [6.91538843e-310 6.91537208e-310 2.75859453e-313 4.94065646e-324
  4.64333467e-310 9.88131292e-324 4.64333467e-310 4.64333467e-310
  8.39911598e-323 4.64333276e-310]
 [4.64333467e-310 8.39911598e-323 4.88059032e-313 6.91515988e-310
  4.64333276e-310 4.88059032e-313 8.39911598e-323 5.51718906e-313
  4.64313899e-310 6.91536456e-310]
 [5.51718906e-313 1.48219694e-322 4.88059032e-313 0.00000000e+000
  0.00000000e+000 4.88059032e-313 4.64333467e-310 4.64333467e-310
  4.64333467e-310 2.75859453e-313]
 [2.75859453e-313 4.64333467e-310 4.64333467e-310 4.64333467e-310
  0.00000000e+000 0.00000000e+000 4.94065646e-324 4.94065646e-324
  4.64333467e-310 6.91538928e-310]
 [4.94065646e-324 6.91536456e-310 9.88131292e-324 4.94065646e-324
  4.64333467e-310 0.00000000e+000 0.00000000e+000 1.38338381e-322
  6.91538209e-310             nan

The **zeros** function can be used to create arrays initialized with 0 values: 

In [12]:
x_1d_zeros = np.zeros(10)
print(x_1d_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
x_2d_zeros = np.zeros((10,10))
print(x_2d_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


The **ones** function behaves like **zeros** functions but initializes the array with 1 values. 

The **full** function creates arrays initialized with a specific value and various dimensions:

In [14]:
x_1d_full = np.full(10, -1)
print(x_1d_full)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [15]:
x_2d_full = np.full((10,10), -1)
print(x_2d_full)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


An array can be also created with random-initialized content by using **random** function from **numpy.random** package:

In [16]:
x_1d_random = np.random.random(10)
print(x_1d_random)

[0.04303317 0.31710633 0.40408887 0.77882259 0.46758117 0.71016737
 0.81130166 0.64212128 0.92576775 0.43471076]


In [17]:
x_2d_random = np.random.random((10, 10))
print(x_2d_random)

[[0.54834111 0.21788422 0.50459118 0.51592741 0.45142174 0.62521712
  0.09501313 0.45475236 0.88382963 0.87382058]
 [0.72625776 0.8899127  0.47796235 0.33961821 0.22857085 0.95907264
  0.10297234 0.15312213 0.73921327 0.20523489]
 [0.8016268  0.84449422 0.71989535 0.30135064 0.36957848 0.88956218
  0.12520935 0.39864971 0.22173271 0.14421549]
 [0.70106214 0.60807758 0.49377785 0.18919069 0.6889121  0.07565877
  0.56670813 0.65346731 0.69254836 0.95936245]
 [0.22265603 0.94846024 0.13662527 0.8881592  0.51837143 0.37423403
  0.80740152 0.34124393 0.0552093  0.84004056]
 [0.07760896 0.95070096 0.84462782 0.88546082 0.49372727 0.67378192
  0.19729928 0.3858644  0.2161782  0.18501099]
 [0.56550659 0.43924628 0.91906861 0.43988317 0.46684308 0.98834589
  0.13145364 0.23934865 0.34957003 0.63238829]
 [0.68239    0.08321116 0.42386588 0.64545973 0.36727261 0.7952752
  0.90359897 0.92808859 0.88973901 0.75892394]
 [0.54508515 0.23474278 0.29910341 0.92100936 0.68658713 0.71020611
  0.45570278 

## 3. Creating via data loading

Numpy allows loading text-based data (in principle CSV data) via the **loadtxt** function. This function allows specification of the parameters for loading operation such as: rows to be skipped, the data delimiter or a complex numpy type to be associated with the data. 

In [18]:
# import packages for remote data load
import requests
import io

# read data remotely
data_url = "https://raw.githubusercontent.com/INTERTECHNICA-BUSINESS-SOLUTIONS-SRL/Applying-Python-in-Machine-Learning/master/notebooks/data/numpy_002_creating_arrays_happines_rank_2020.csv"
response = requests.get(data_url)

# load the string data into a record array
loaded_data = np.loadtxt(
    io.StringIO(response.text), 
    skiprows = 1, 
    delimiter = ",", 
    dtype = {"names" : ("Country", "Rank", "Score", "Population"),
            "formats": ("U20", "int8", "float16", "float32")}
)

In [19]:
print(loaded_data.shape)

(152,)


In [20]:
print(loaded_data[0])

('Finland', 1, 7.77, 5540.72)


In [21]:
print(loaded_data["Country"])

['Finland' 'Denmark' 'Norway' 'Iceland' 'Netherlands' 'Switzerland'
 'Sweden' 'New Zealand' 'Canada' 'Austria' 'Australia' 'Costa Rica'
 'Israel' 'Luxembourg' 'United Kingdom' 'Ireland' 'Germany' 'Belgium'
 'United States' 'Czech Republic' 'United Arab Emirates' 'Malta' 'Mexico'
 'France' 'Taiwan' 'Chile' 'Guatemala' 'Saudi Arabia' 'Qatar' 'Spain'
 'Panama' 'Brazil' 'Uruguay' 'Singapore' 'El Salvador' 'Italy' 'Bahrain'
 'Slovakia' 'Trinidad and Tobago' 'Poland' 'Uzbekistan' 'Lithuania'
 'Colombia' 'Slovenia' 'Nicaragua' 'Argentina' 'Romania' 'Ecuador'
 'Kuwait' 'Thailand' 'Latvia' 'South Korea' 'Estonia' 'Jamaica'
 'Mauritius' 'Japan' 'Honduras' 'Kazakhstan' 'Bolivia' 'Hungary'
 'Paraguay' 'Cyprus' 'Peru' 'Portugal' 'Pakistan' 'Russia' 'Philippines'
 'Serbia' 'Moldova' 'Libya' 'Montenegro' 'Tajikistan' 'Croatia'
 'Hong Kong' 'Dominican Republic' 'Bosnia and Herzegovi' 'Turkey'
 'Malaysia' 'Belarus' 'Greece' 'Mongolia' 'Nigeria' 'Kyrgyzstan'
 'Turkmenistan' 'Algeria' 'Morocco' 'Azerbaij

In [22]:
print(loaded_data[-1]["Country"])

South Sudan
