![*INTERTECHNICA - SOLON EDUCATIONAL PROGRAMS - TECHNOLOGY LINE*](https://solon.intertechnica.com/assets/IntertechnicaSolonEducationalPrograms-TechnologyLine.png)

# Python for Data Processing - Array Broadcasting

*Numpy facilitates operations between arrays of different shapes. This mechanism is called array broadcasting*.

By default arithmetic operations (such as addition or subtraction) **are meaningful only for arrays of the same or compatible dimensions**. Numpy allows such operations for some arrays which have different and incompatible dimensions by using the broadcasting mechanism.  

The rules of broadcasting are explained in the original documentation as follows:

> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
>
> * they are equal 
> or
> * one of them is 1



Initializing environment for machine learning use:

In [1]:
!python -m pip install numpy

## 1. Broadcasting with scalars

The broadcast mechanism will broadcast a scalar to the shape of the target array and will perform the operation.

In [2]:
import numpy as np

In [3]:
x_1d = np.array([ 1,   2,   3,   4,   5,   6,   7,   8,   9,  10])
scalar1 = 2

x_1d_multiplied = x_1d * scalar1

print(x_1d_multiplied)

[ 2  4  6  8 10 12 14 16 18 20]


In the example above the scalar with the value 2 was broadcasted to the array [2, 2, 2, 2, 2, 2, 2, 2, 2, 2] so that its dimensionality matches the one of the target array. This is equivalent to the code bellow:

In [4]:
scalar_1_broadcasted = np.full(10, 2)

x_1d_multiplied_explicit_broadcast = x_1d * scalar_1_broadcasted

print(x_1d_multiplied_explicit_broadcast)

[ 2  4  6  8 10 12 14 16 18 20]


The same can be done with two-dimensional or other multidimensional arrays:

In [5]:
x_2d = np.array(
      [[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

scalar2 = 2

x_2d_power = x_2d ** 2

print(x_2d_power)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


## 2. Broadcasting with arrays

The broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:


* **Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
* **Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
* **Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


Let's consider the following case of arrays with different dimensions

In [6]:
lh_array = np.array([1,1])
print(lh_array.shape)

(2,)


In [7]:
rh_array = np.array([[2,3], [4,5]])
print(rh_array.shape)

(2, 2)


The left hand array will be **broadcasted** to the right hand array by duplicating the first row.

![Array Broadcasting](https://raw.githubusercontent.com/INTERTECHNICA-BUSINESS-SOLUTIONS-SRL/Applying-Python-in-Machine-Learning/master/notebooks/assets/array_broadcasting.png)

In [8]:
result_array = rh_array + lh_array
print("The shape of result array is: {}".format(result_array.shape))
print("The shape of result array is: \n {}".format(result_array))

The shape of result array is: (2, 2)
The shape of result array is: 
 [[3 4]
 [5 6]]
